require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

AllCops:
  NewCops: enable

Style/SymbolArray:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/WordArray:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
