require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/universes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Universe. As you add validations to Universe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Universe.create! valid_attributes
      get universes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      universe = Universe.create! valid_attributes
      get universe_url(universe)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_universe_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      universe = Universe.create! valid_attributes
      get edit_universe_url(universe)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Universe" do
        expect {
          post universes_url, params: { universe: valid_attributes }
        }.to change(Universe, :count).by(1)
      end

      it "redirects to the created universe" do
        post universes_url, params: { universe: valid_attributes }
        expect(response).to redirect_to(universe_url(Universe.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Universe" do
        expect {
          post universes_url, params: { universe: invalid_attributes }
        }.to change(Universe, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post universes_url, params: { universe: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested universe" do
        universe = Universe.create! valid_attributes
        patch universe_url(universe), params: { universe: new_attributes }
        universe.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the universe" do
        universe = Universe.create! valid_attributes
        patch universe_url(universe), params: { universe: new_attributes }
        universe.reload
        expect(response).to redirect_to(universe_url(universe))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        universe = Universe.create! valid_attributes
        patch universe_url(universe), params: { universe: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested universe" do
      universe = Universe.create! valid_attributes
      expect {
        delete universe_url(universe)
      }.to change(Universe, :count).by(-1)
    end

    it "redirects to the universes list" do
      universe = Universe.create! valid_attributes
      delete universe_url(universe)
      expect(response).to redirect_to(universes_url)
    end
  end
end
